pub use self::challenge1::Challenge1;
pub use self::challenge2::Challenge2;
pub use self::challenge3::Challenge3;
pub use self::challenge4::Challenge4;
pub use self::challenge5::Challenge5;
pub use self::challenge6::Challenge6;
pub use self::challenge7::Challenge7;
mod challenge1;
mod challenge2;
mod challenge3;
mod challenge4;
mod challenge5;
mod challenge6;
mod challenge7;
